name: Tests and Linting

on:
  pull_request:

jobs:
  run-pytest-and-lint:
    runs-on: ubuntu-latest
    env:
      # to disable GPU usage during tests
      CUDA_VISIBLE_DEVICES: ""
    steps:
      - name: Check out source repository
        uses: actions/checkout@v6

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
            enable-cache: false

      - name: Install dependencies
        run: |
          uv venv
          uv pip install setuptools --upgrade # to avoid build issues
          uv pip install torch --index-url https://download.pytorch.org/whl/cpu --upgrade 
          uv pip install -e ".[dev]"

      - name: Pytest
        run: uv run pytest

      - name: Ruff check
        run: uv run ruff check . --output-format=github